#!/bin/bash

CCT='{
  "compilation": {
    "az": "z1",
    "network": "default",
    "reuse_compilation_vms": true,
    "vm_type": "default",
    "workers": 5
  },
  "disk_types": [
    {
      "disk_size": 1024,
      "name": "1GB"
    },
    {
      "disk_size": 5120,
      "name": "5GB"
    },
    {
      "disk_size": 10240,
      "name": "10GB"
    },
    {
      "disk_size": 100240,
      "name": "100GB"
    },
    {
      "disk_size": 1024,
      "name": "default"
    }
  ],
  "networks": [
    {
      "name": "default",
      "subnets": [
        {
          "azs": [
            "z0",
            "z1",
            "z2"
          ],
          "cloud_properties": {
            "name": "bridge"
          }
        }
      ],
      "type": "dynamic"
    }
  ],
  "vm_extensions": [
    {
      "name": "5GB_ephemeral_disk"
    },
    {
      "name": "10GB_ephemeral_disk"
    },
    {
      "name": "50GB_ephemeral_disk"
    },
    {
      "name": "100GB_ephemeral_disk"
    },
    {
      "name": "500GB_ephemeral_disk"
    },
    {
      "name": "1TB_ephemeral_disk"
    },
    {
      "name": "cf-router-network-properties"
    },
    {
      "name": "diego-ssh-proxy-network-properties"
    },
    {
      "name": "cf-tcp-router-network-properties"
    },
    {
      "name": "haproxy-network-properties",
      "cloud_properties": {
        "PortBindings": {
          "2222/tcp": [{ "HostPort": "2222", "HostIp": "0.0.0.0" }],
          "80/tcp": [{ "HostPort": "80", "HostIp": "0.0.0.0" }],
          "443/tcp": [{ "HostPort": "443", "HostIp": "0.0.0.0" }]

        },
        "ports": [
          "2222/tcp",
          "80/tcp",
          "443/tcp"
        ]
      }
    }

  ],
  "vm_types": [
    {
      "name": "minimal",
      "cloud_properties": {
        "RestartPolicy": {
          "Name": "always"
        }
      }
    },
    {
      "name": "small",
      "cloud_properties": {
        "RestartPolicy": {
          "Name": "always"
        }
      }

    },
    {
      "name": "small-highmem",
      "cloud_properties": {
        "RestartPolicy": {
          "Name": "always"
        }
      }
    },
    {
      "name": "default",
      "cloud_properties": {
        "RestartPolicy": {
          "Name": "always"
        }
      }
    }
  ]
}'

CC=$(terraform output -json | jq -c -r --argjson CC "$CCT" '. as $root
  | $root.nodes.value[0] | to_entries | map({
    name: "z\(.key)",
    cpi: "docker-z\(.key)",
  }) | {azs: .} as $azs
  | $root.flannel_cidrs.value[0] | to_entries | map({
    range: .value,
    gateway: (.value | sub("0/24"; "1")),
    reserved: [ "\(.value | sub("0/24"; "2")) - \(.value | sub("0/24"; "10"))" ],
    az: "z\(.key)",
    cloud_properties: { name: "bosh" }
  }) | {networks: [{
    name: "default",
    type: "manual",
    subnets: .,
  }]} as $networks
  | ($CC | to_entries) + ($azs | to_entries) + ($networks | to_entries) | from_entries')

echo "bosh update-cloud-config <(echo '$CC')"
