#!/bin/bash

CPIS=$(terraform output -json | jq -c -r '. as $root | $root.nodes.value[0] | to_entries | map({
  name: "docker-z\(.key + 1)",
  type: "docker",
  properties: {
    docker: {
      host: "tcp://\(.value):2376",
      api_version: 1.38,
      tls: {
        ca: $root.docker_ca.value,
        certificate: $root.docker_client_cert.value,
        private_key: $root.docker_key.value
      }
    }
  }
}) | {cpis: .}')

echo "bosh update-cpi-config <(echo '$CPIS')"
