#!/bin/bash

terraform output -json | jq -r '.docker_client_cert.value' > ~/.docker/cert.pem
terraform output -json | jq -r '.docker_ca.value' > ~/.docker/ca.pem
terraform output -json | jq -r '.docker_key.value' > ~/.docker/key.pem

for host in $(terraform output -json | jq -r '.nodes.value[0][]'); do
    tmux split-window -h "DOCKER_HOST=tcp://${host}:2376 docker --tls run --rm -ti \
    --name=ctop \
    --volume /var/run/docker.sock:/var/run/docker.sock:ro \
    quay.io/vektorlab/ctop:latest"
done

tmux select-layout even-horizontal
