#!/bin/bash


git clone -b develop https://github.com/starkandwayne/bucc.git
pushd bucc
mkdir -p operators
cat > "./operators/9x-bosh-docker-cpi.yml" <<YML
- type: replace
  path: /releases/name=bosh-docker-cpi?
  value:
    name: bosh-docker-cpi
    url: file:///tmp/bosh-docker-cpi.tgz
YML
popd

git clone -b dynamic-network-fixes https://github.com/rkoster/bosh-docker-cpi-release.git
pushd bosh-docker-cpi-release
bosh create-release --tarball /tmp/bosh-docker-cpi.tgz
popd

./dev/bucc_vars | yq r - > dev/bucc/vars.yml
./dev/docker
