jobs:
- name: update-molten-core
  public: true
  serial: true
  plan:
  - do:
    - get: moltencore-github-release
      trigger: true
    - get: packet-molten-core
    - task: build-binary
      config:
        platform: linux
        image_resource:
          type: registry-image
          source: {repository: starkandwayne/concourse}
        inputs:
        - name: packet-molten-core
          path: repo
        - name: moltencore-github-release
          path: release
        outputs:
        - name: repo
        run:
          path: /bin/bash
          args:
            - -ce
            - |
              wget -O ct https://github.com/coreos/container-linux-config-transpiler/releases/download/v0.9.0/ct-v0.9.0-x86_64-unknown-linux-gnu
              chmod +x ct
              pushd repo
              ../ct -out-file templates/config.ign \
              -platform packet -pretty -strict \
              -in-file <(bosh int ../release/container-linux-config.yaml -o ci/packet-clc.yml)
              sed -i 's/${/$${/g' templates/config.ign
              sed -i 's/ETCD_DISCOVERY_PLACEHOLDER/${discovery_url}/g' templates/config.ign
              git config --global user.email "ci@starkandwayne.com"
              git config --global user.name "CI Bot"
              git add -A && git commit -m "Updating to MoltenCore: $(cat ../release/version) "
    - put: packet-molten-core
      params:
        repository: repo
        merge: true

resources:
- name: moltencore-github-release
  type: github-release
  source:
    owner: starkandwayne
    repository: molten-core
    access_token: ((github_access_token))

- name: packet-molten-core
  type: git
  source:
    branch: master
    uri: https://github.com/starkandwayne/packet-molten-core.git
    username: ((github_user_name))
    password: ((github_access_token))
